version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    # ...

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    # ...

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bnka
    ports:
      - "3306:3306"
    # ...

networks:
  my_network:
